### ISSUE TITLE
authentication error after not changing password for 60 days

### ISSUE THREAD

**Issue by zzysunny** [ohmantics/homebridge-airmega#5]
Coway prompts users to change passwords after sixty days. homebridge-airmega does not handle this prompt and leads to an authentication error. I resolved the issue by logging out of the IoCare app and logging back in, where I was greeted with the change password prompt. I chose the option to remind me in 30 days and rebooted homebridge - plug-in works after. Unfortunately, I did not save the debug error logs before rebooting, but the issue should be consistently reproducible if password prompt is present.

**Comment by ohmantics** [comment]
Thanks. I got warning of this just a day ago from @RobertD502.

When it happens to me, I'll be able to save enough logs to work with. I'm hoping we can just automatically press the Not Now button indefinitely.

If in the meantime somebody with the debug flag enabled is able to capture those logs, that would help. Please do not post them here because they contain Personally Identifiable Information (PII) that need to be manually scrubbed out. We'll connect via Discord or something and I'll walk you through that process.

**Comment by flochtililoch** [comment]
I'm able to reproduce and have a debug trace - would be happy to connect to get help filtering out my PII before sending over. Let me know what's the best way to do that.

**Comment by ohmantics** [comment]
@flochtililoch Find me on the [Homebridge Discord](https://discord.com/invite/Z8jmyvb). I'm "alexr#3338".

**Comment by ohmantics** [comment]
I've put up a pull request at https://github.com/ohmantics/homebridge-airmega/pull/8.

**Comment by ohmantics** [comment]
The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ohmantics/homebridge-airmega/v/3.4.0)
- [GitHub release](https://github.com/ohmantics/homebridge-airmega/releases/tag/v3.4.0)
